# example netlify.toml
[build]
  command = "pnpm run build"
  functions = "netlify/functions"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = '20.5.1'
  AWS_LAMBDA_JS_RUNTIME = 'nodejs18.x'

  [[redirects]]
    from ="/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[dev]
  command = "pnpm dev" # Command to start your dev server
  port = 4173 # Port that the dev server will be listening on
  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://docs.netlify.com/configure-builds/file-based-configuration/

[context.dev]
  environment = { NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true" }
